# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  REACT_APP_SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_SECRET }}
  REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn build
      - name: Verificar contenido del directorio de construcción
        run: ls -l build
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Verificar contenido del directorio actual antes del despliegue
        run: ls -l

      - name: Navegar al directorio del proyecto
        run: cd $GITHUB_WORKSPACE/song-search

      - name: Verificar contenido del directorio actual después de la navegación
        run: ls -l

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project search-song-api-spotify
